### ISSUE TITLE
English API documentation ?

### ISSUE THREAD

**Issue by juba** [timelyportfolio/g2r#6]
Hi,

Sorry, this is not directly related to the R implementation, but do you know if there is an english version of the API documentation ? Beside a simple tutorial I've only managed to find one in chinese.

Thanks !

**Comment by timelyportfolio** [comment]
no unfortunately only Chinese for now, so relying on Google Translate

**Comment by timelyportfolio** [comment]
going to close for now to stay on top of issues.  Thanks, and I'd love your input along the way.
